---
title: "p8105_hw6_kz2334"
author: "Kangkang Zhang"
output: github_document
---

Load required packages.

```{r set up, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

library(tidyverse)
library(viridis)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```


##Problem 1

Import the data. 
```{r 1.1 import, message = FALSE} 
homicide_data = read_csv("./data/homicide-data.csv")
```

Create a city_state variable, and a binary variable indicating whether the homicide is solved. 

```{r 1.2}
homicide_data = homicide_data %>% 
  mutate(city_state = str_c(city, ", ", state),
         status = ifelse(disposition %in% c("Closed without arrest", "Open/No arrest"), 0, 1))
```

Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake.

```{r 1.3}
homicide_data = homicide_data %>% 
  filter(!(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Tulsa, AL"))) %>% 
  mutate(victim_race = ifelse(victim_race == "White", "white", "non-white"),
          victim_race = as.factor(victim_race), 
            victim_race = relevel(victim_race, ref = "white"))
  
```

